# Generated by Django 4.2.3 on 2023-10-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapp', '0002_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name2', models.CharField(max_length=250)),
            ],
        ),
    ]
